Section "Device"
    Identifier "virtio"
    Driver "modesetting"
EndSection

Section "Monitor"
    Identifier "Monitor0"
    Option "PreferredMode" "1920x1080"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "virtio"
    Monitor "Monitor0"
    DefaultDepth 24
    SubSection "Display"
        Virtual 1920 1080
    EndSubSection
EndSection
